baseURL = "http://www.tekstikaeve.ee/"			# Site's URL
disqusShortname = "kristel"                        # Your disqus shortname
googleAnalytics = "UA-108858524-1"
title = "Tekstikaeve"								# Site's Name
theme = "manis-hugo-theme"
copyright = "&copy; 2017 Kristel Uiboaed"	# Copyright notice. Note: You can use HTML tag here
pluralizeListTitles = false
paginate = 10								# Minimum number of item before paginate navigation show up
canonifyURL = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[taxonomies]
	tag = "tags"


[params]
	debugCSS = false                        # If false, use minified CSS (ui.min.css)
	disqusSections = ["blog"]               # list of section support disqus comments
	# Site meta description
	description = "Andmeteadus, keeleteadus, tekstikaeve, loomuliku keele töötlus, andmeanalüüs, andmete visualiseerimine, R, Python"
	tagline = "Andmeteadus, keeleteadus, tekstikaeve, loomuliku keele töötlus, andmeanalüüs, andmete visualiseerimine, R, Python"   # Site's Tagline (Subtitle or Keyword)
	themeAttrib = true                      # If true give attribution to this theme
	licenseURL = "/about/license"           # URL to license file, can be outside of your domain

	# 404 Configuration
	head404 = "Sorry, I can find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	colorTheme = "#ffb700"                  # Color of your website
	latestCount = 3                         # Maximum number of item in Latest Posts or Works
	faviconImg = ""                         # Path to site's favicon image
	dateFmt = "02/01/2006"                # Date format in item list

	# Code Highlighting (HighlightJS)
	highlightJs = true
	highlightJsLanguages = [ "r" ]
	highlightJsStyle = "ocean"

	# Social Links
	email = "kristel.uiboaed@gmail.com"
	github = "https://github.com/kristel-/"
	twitter = "https://twitter.com/kristel_UI"


# Language Configuration
defaultContentLanguage = "en"
# Edit this if you want to translate your blog
#[languages.in]
#	lang = "in"
#	languageName = "Bahasa Indonesia"
#	weight = 1
